server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.27.171.107:3306/payApp?characterEncoding=utf8&useSSL=false
    username: root
    password: 741623
  redis:
    database: 0
    host: 119.27.171.107
    port: 6379
    timeout: 500
    password: 741623

mybatis:
  mapper-locations: classpath:com/edu/graduation/mapper/*.xml
  type-aliases-package: com.edu.graduation.entity.bean

